'client'
import Navbar from './componentes/Navegacion'
import Footer from './componentes/Footer'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'



const inter = Inter ({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar />
        {children}
        <Footer />
      </body>

    </html>
  )
}
